### PR TITLE
Allow preview docs to be pushed on PRs

### PR DESCRIPTION
**Pull request by asinghvi17**
see https://github.com/JuliaDocs/Documenter.jl/pull/1180

### CODE REVIEW

**Comment by Datseris** [comment]
oh that is awesome! How do I actually see the doc preview though?

**Comment by Datseris** [comment]
https://juliadynamics.github.io/DrWatson.jl/previews/PR125 doesn't work. Maybe we have to modify the Project.toml of the documentation to use latest documenter?

**Comment by Datseris** [comment]
ping @asinghvi17 ?

**Comment by asinghvi17** [comment]
Looks like Travis doesn't even get to the documentation stage for some reason.  Not sure why, but I don't have enough Travis knowledge to really tell :D.

**Pull request merged**
