### PR TITLE
Recursive digits/scientific precision in savename

### PR DESCRIPTION
**Pull request by PhilipVinc**

### CODE REVIEW

**Comment by Datseris** [comment]
Cool, please increment patch version number in the Project.toml file.

**Comment by PhilipVinc** [comment]
done!
Sorry for the no-comment PR.
I had done this before heading home on Friday...
But I'd say fixes a bug

**Comment by Datseris** [comment]
no prob!

**Comment by PhilipVinc** [comment]
I think I bumped to 1.9.1->1.9.2, but 1.9.1 had never been released

**Comment by Datseris** [comment]
Ops, sorry, that was my bad. I've just added a tag for 1.9.1!

**Pull request merged**
