### PR TITLE
[WIP] JuliaDynamics documentation theme

### PR DESCRIPTION
**Pull request by Datseris**
Okay, this PR attempts to create a Documenter.jl theme that will be subsequently used in all packages of JuliaDynamics. I invite everyone to provide feedback and comments and suggestions etc. The documentation can be previewed here:

https://juliadynamics.github.io/DrWatson.jl/previews/PR127/

I guess if there is one thing that is non-negotiable, its the color purple... :D 

The theme should be compared with e.g. the theme of DynamicalSystems.jl (as it will get the same theme as well): https://juliadynamics.github.io/DynamicalSystems.jl/dev/

### CODE REVIEW

**Comment by asinghvi17** [comment]
The changes here seem to have overridden the background colour for code blocks - this looks especially bad 😆 
Screen Shot 2020-02-15 at 2 15 42  30400PM

**Comment by Datseris** [comment]
Yeap @asinghvi17 I know. I don't know how to fix it, I've asked @mortenpi and a reply is pending. I've overwritten the "correct" .css command but it didn't affect it.

**Comment by asinghvi17** [comment]
Also, the URLs on the front page seem broken.

**Comment by cormullion** [comment]
Looking at the first link (is this before or after the makeover?) -  Personal opinion: I'm not a big fan of this: too many strong colours, poor contrast, sidebar is particularly low contrast, font isn't great for reading, pale green headings get lost but should be catching the eye. I presume the code samples have gone wrong?

The dark theme is better - but the  admonitions are a bit distracting when you're trying to read (the main purpose?). OK for serious warnings perhaps...

I like purple. But small intense accents are better than huge expanses or wide headers... There's way too much of it for me. If you provide an alternative monochrome look I'll definitely be using it. :)

**Comment by Datseris** [comment]
Damn, this is so harsh I will cry! No just kidding, this isn't nowhere near the final product and if noone likes it it goes in the garbage anyway.

I've tried to use purple color for the sidebar, because I want to mirror the look of the original doc of DynamicalSystems.jl (and also DynamicalBilliards.jl) here: https://juliadynamics.github.io/DynamicalSystems.jl/dev/ , but you think its too much? In the Material case, the purple bar is much smaller in size, but I think one cannot achieve a similar effect with Documenter.

For the admonitions, I guess you have a point, there are too many in the start. 

> poor contrast, sidebar is particularly low contrast, font isn't great for reading, 

What is the poor contrast? between purple and white, or between the side bar and the main part? About the font, sure, feel free to suggest better alternatives for both code and normal text. These are the fonts used in the DynamicalSystems.jl docs, and I haven't had any trouble reading that so far...

**Comment by cormullion** [comment]
Sorry if I sounded a bit harsh! 😿The previous docs are better as far as contrast is concerned. It's worth remembering that design is for others not just for us - perhaps people have weaker eyes or colour blindness or whatever.

You can test sonethings online - eg here: https://color.a11y.com/Contrast/ .

**Comment by Datseris** [comment]
DOn't worry, I really appreciate your critisism, and the harsher the better. THe old website unfortunately is made with a Python package that always brings problems into building the docs both online as well as locally... So a move to Documenter will make things easier. But the won't be as cool. If you have some spare time at any point please feel welcomed to suggest better fonts, and better style choices.

In the mean time, I will try to make the left side bar to not be full purple, but to only have the purple at e.g. the currently selected section.

**Comment by Datseris** [comment]
In the latest commit I've decreased saturation significantly, and decreased the total amount of color used to only 4 (besides the admonition blocks). I tried other fonts as well, but MOntserrat always appeard more readable to me. I've tried e.g. Quicksand, Lora, Lato

**Comment by asinghvi17** [comment]
The font color for subsections in the sidebar is white...I can't read it at all with the white background.  May want to change them to black?

**Comment by Datseris** [comment]
> At the moment a documenter bug does not correctly register where the colors of the text of the sidebar should come from.

It is supposed to be white but documenter fail to configure it. But okay, you have a point, for now I'll make all black.

**Comment by asinghvi17** [comment]
Just looked at the preview docs again, they look pretty good!  Did have one small quibble - the colour of hyperlinks is a little too light for the background, as in the image below.  Perhaps they could be darkened?

Screen Shot 2020-02-15 at 11 32 22  03200PM

**Comment by Datseris** [comment]
I am very happy with the current state of the visuals of the docs. There are only minor things that I am looking to change, like .e.g not having sidebar shadow on the white part of the sidebar, and finally fixing the code background to be a very light purple color.

Thus it is time for review. @cormullion feel free to look again as well.

**Comment by asinghvi17** [comment]
Looks good.  Last problem, I promise ;) - hyperlinks in code blocks are a bit hard to read.

Screen Shot 2020-02-16 at 3 59 18  59800PM

**Comment by Datseris** [comment]
Style choice question: should the background of the code blocks be (a) in the "secondary" color (the bluish color the links have) like this:

image

or in the main color (here, purple), like this:

image

**Comment by Datseris** [comment]
> Looks good. Last problem, I promise ;) - hyperlinks in code blocks are a bit hard to read.

@asinghvi17 sure, but what is the problem? Their color or the fact that they are in bold?

**Comment by asinghvi17** [comment]
I think it's the colour, mostly - the contrast is too low IMO

**Comment by Datseris** [comment]
I am very happy with this and I consider it the final product. I'll let this "simmer" here for a couple of days, until the rest of the JuliaDynamics people see this and give final feedback for fonts, colors, etc. I personally would find the hyperlinks more readable if they were lighter, but I've made them progressively darker throughout this feedback process. 

Then I'll make a repo in JuliaDynamics that only has the styling `scss` file, which all other repos will download and build the docs with. This will make it easier to make changes to the theme instead of the individual docs.

@ChrisRackauckas this might be interesting for you as well!

**Comment by sebastianpech** [comment]
In my opinion the hover in the submenus is a bit much, also the padding is off
image

Besides that, I think you did a great job. Contrast is fine, a bit colorful for my taste ;)

**Comment by cormullion** [comment]
article-2120189-125551F0000005DC-168_964x428

:)

**Comment by asinghvi17** [comment]
The Manifest might need to be removed before merging?  At the least, it should be fixed to the `mp/theming` branch of Documenter or something...seems to be causing CI to fail now.

**Comment by Datseris** [comment]
This PR won't get merged anyway, don't worry. It is only a test. The docstyling files will be centrally distributed from another repo in JuliaDynamics

**Comment by asinghvi17** [comment]
Actually, there is one bug on dark theme:
Screen Shot 2020-02-19 at 2 59 54  70500PM

**Comment by Datseris** [comment]
This is good to go. I'll wait for the Documenter PRs to be merged and then I'll put this in effect. In the meantime, everyone is invited to also look at the dark theme and give feedback.

**Pull request merged**
