### PR TITLE
WIP: backup existing files instead of overwriting them

### PR DESCRIPTION
**Pull request by JonasIsensee**
This addresses #28 

This is basic functionality without integration into the other algorithms.

The idea is inspired by GROMACS.
If the `test.bson` to be saved to already exists,
the old file will be moved to `#1#_test.bson`.
If this one exists already as well, the file previously called `#1#_test.bson` will be renamed to `#2#_test.bson`.

The newest file is always called `test.bson` oldest file is called `#42#_test.bson` (if there are 43 saved files in total).

What do you think?

### CODE REVIEW

**Comment by Datseris** [comment]
Hi Jonas! This is really nice! I really like this and will definitely review "properly" and merge once this has tests implemented! You might want to write a basic doc-string as well. I can improve it if need be.

I assume you have checked and indeed one can use `#` in file names in all major operating systems, right?

I am not sure about how this:
```
run(`mv $cur_path $new_path`)
```
Why do you have to use the command line in the first place? You can use pure Julia code from the FileSystem module here: https://docs.julialang.org/en/latest/base/file/#Base.Filesystem.mv the funciton `mv` exists already. Please consider doing that; it will save us a lot of headaches later on.

We can see about integrating this elsewhere as well, but let's put in some basic tests and docs first. I assume having a keyword `safe = true` for e.g. `tagsave` would be nice from an API perspective.

---

I am confused about this addressing #28. Maybe you got confused. #28 is only for re-processing the data that are already existing in the collection dataframe. It is not about saving the file of the dataframe itself. For example let's say I have already processed files `a` and `b` (and thus these files are in the `:path` column) but I want to _reprocess_ them so I can use e.g. the `special_list` argument.

**Comment by Datseris** [comment]
I would also change the main function name from `save_safely` to `safesave`

**Comment by Datseris** [comment]
Another thing that I believe can be improved: the position of the numbering scheme. Currently it is always in the start, but this makes for a bad displaying in the containing folder. Since most OS sort files alphabetically the "new (old)" files with `#` will be far away from the new new files. 

Isn't it a better approach to put the number scheme before the file ending? E.g. before `.bson`. So `test.bson` will become `test_#1#.bson` ? In addition, is there a reason for the second `#`? Isn't `test_#1.bson` enough due to Regex? Because if it is enough we should do it like this; the less characters in a file's name the better it is.

p.s.: the file separator position can be found by:
```julia
a = "test.ka.bson"
s = findall(isequal('.'), a)[end]
```

**Comment by JonasIsensee** [comment]
Indexing into strings is BAD. I found a different solution using regexp though.
Let's just hope, no one wants to use a file type that has two suffixes.
Wouldn't want any `.tar.gz` be renamed to `.tar#1.gz` ....

All common file systems seem to support # in filenames.

**Comment by JonasIsensee** [comment]
Uh... a rebase seems to really spam github.
Sorry about that.

I'm done here.
There are two merge conflicts here that I can't seem to resolve.
Github claims that my code conflicts with an empty line on master
but I can't reproduce that locally.

**Comment by Datseris** [comment]
@JonasIsensee Something happened on GitHub that I cannot comprehend. GitHub initially told me that you have created _new_ files for your new code. So in my conflict resolution I removed conflicting parts. But now the code is gone. Whaaat!!!

Also since there seem too many unnecessary commits. Did you try to rebase into your local master, which was unsynced for a month?

In any case, the easiest way forward is to close this and simply open a new PR. Can you please do that? (By the way you have push access to DrWatson.jl).

**Pull request closed without merging**
