### PR TITLE
Update sumatra-part

### PR DESCRIPTION
**Pull request by tamasgal**
Targets the Sumatra part in the latest review comment on the paper: https://github.com/openjournals/joss-reviews/issues/2673#issuecomment-714517043

### CODE REVIEW

**Comment by Datseris** [comment]
Can we add the 

> I think ReproZip and ActivePapers should be mentioned in the "Comparison" section, as tools which also aim to make scientific projects easily portable, but in more language-independent ways.

part here almost verbatim? Seems like the simplest way to address.

**Comment by Datseris** [comment]
Also, _faaaaast_.

**Comment by tamasgal** [comment]
Not sure about ActivePapers; that project seems quite dead to me...

**Comment by Datseris** [comment]
> Not sure about ActivePapers; that project seems quite dead to me...

That is good enough justification. After all we have to _reply_ to a review, not absolutely do what it says.

**Comment by tamasgal** [comment]
:+1:

**Pull request merged**
