### PR TITLE
add Pluto.jl to notebooks packages

### PR DESCRIPTION
**Pull request by kescobo**

### CODE REVIEW

**Comment by sebastianpech** [comment]
Is it actually working with DrWatson? First time I tried I couldn't activate the project.

**Comment by kescobo** [comment]
Ahh, good question, I did not check. I actually haven't used Pluto yet myself, but it seems to be the new hotness. If it's not working, would be nice to look into it, but OK with me to close this pending that investigation.

**Comment by sebastianpech** [comment]
I will check today. I think they recently did some work on supporting environments.

**Comment by sebastianpech** [comment]
Yep. Works now.

**Pull request merged**
