### PR TITLE
Included julia-compat

### PR DESCRIPTION
**Pull request by pmk21**
Addresses #91

### CODE REVIEW

**Comment by sebastianpech** [comment]
um ... have you tested your code? You are missing a `"`

`"[compat]" * "\njulia = \"v" * string(VERSION) * "\""`

**Comment by pmk21** [comment]
Sorry my bad missed that quote. I will fix it right away and make it cleaner.

**Comment by Datseris** [comment]
@pmk21 can you please increment the version in the Project.toml file? This is worthy of an immediate release! :)

**Comment by pmk21** [comment]
Yes I will. Increment the version to?

**Comment by sebastianpech** [comment]
The one in Project.toml
https://github.com/JuliaDynamics/DrWatson.jl/blob/8aef17d26685e3dc6c57382814bb49d81161759c/Project.toml#L4
and then add the new version with your change to https://github.com/JuliaDynamics/DrWatson.jl/blob/master/CHANGELOG.md

**Pull request merged**
