### PR TITLE
replace bson with jld2

### LINKED ISSUE #231: Switch all doc to use JLD2.jl instead of BSON.jl
Using BSON.jl in our docs leads newcomers of Julia to using BSON instead of JLD2, which I think is really not a good idea... We should really change it.

p.s.: I'm really surprised that new users come to DrWatson first before even checking out a package to save files :D

### PR DESCRIPTION
**Pull request by Datseris**
Closes #231

### CODE REVIEW

**Comment by Datseris** [comment]
@JonasIsensee could you please help here? I dont remember fully; does JLD2 require that dictionaries must have String type as keys?

**Comment by JonasIsensee** [comment]
Hi @Datseris ,

yes, JLD2 can only store string keys and it is not possible to change that internally
since it follows the HDF5 standard which has an internal file system like representation.


If you want to use `Symbol`s in DrWatson, we have a few workaround options. 
1) Write a new API function that automatically converts to string when writing. The problem is that you need to be explicit about this when loading.

2) Write a new API function that prepends some signal characters e.g. `:param` → `"__param"` which can then be parsed back to symbols upon loading. 
Potential problem:
- If implemented in DrWatson, then the data is different when loaded directly.
- If implemented in JLD2, then it still doesn't integrate so well with the path like structure.

3) JLD2 can store most objects - just not as keys. Something like 
```
function wsave(filename, data...; kwargs...)
   if endswith(filename, ".jld2")
        d = Dict(data)
        FileIO.save(filename, "data", d; kwargs....)
    end
end
```

**Comment by JonasIsensee** [comment]
Step three has the disadvantage that it reduces performance for large files as it becomes impossible to load only parts of a file.
Step two breaks the type stability for the keys of loaded files but maybe that would be acceptable.

**Comment by JonasIsensee** [comment]
I'm implementing something like idea no 2 in https://github.com/JuliaIO/JLD2.jl/pull/287

I don't yet know whether this is really a good idea, though.

**Comment by Datseris** [comment]
wait, which part of DrWatson doesn't allow us to use string keys? I thought it was a simple change from my end, only in the example files. Am I missing something?

**Comment by JonasIsensee** [comment]
I'm sorry if that wasn't clear.
there is a problem on the JLD2 side, IF you want to use `Symbol` keys as you currently do with BSON.

**Comment by Datseris** [comment]
okay. let me first make this PR working (the examples do not work at the moment), and then we can see what is necessary in JuliaIO/JLD2.jl#287 and whether it is necessary at all

**Comment by Datseris** [comment]
@JonasIsensee I've fixed the `workflow.jl` file in the docs, and now it does correctly use `JLD2`. However, it seems that `collect_results!` is not working. Does it make any assumptions regarding the key type?

**Comment by Datseris** [comment]
Okay @JonasIsensee everything is fine. I was doing something else wrong. I'll now update the tests to also use JLD2 instead of BSON and we are good to go. I don't think the modification you are doing in JLD2.jl is necessary and as you said it also has some problems, so I think you can close that PR.

**Comment by JonasIsensee** [comment]
> Okay @JonasIsensee everything is fine. I was doing something else wrong. I'll now update the tests to also use JLD2 instead of BSON and we are good to go. I don't think the modification you are doing in JLD2.jl is necessary and as you said it also has some problems, so I think you can close that PR.

Alright, awesome.
I fixed two more things.
`produce_or_load` still had `bson` as the default suffix and
I updated the real world example. 

That example also shows the string-key limitation of jld2. (That isn't really a big problem)

```
return @dict toypar_h
```

has to now say 
```
return @strdict toypar_h
```

but since 
```
@unpack toypar_h = data
```
doesn't care whether `data` contains string or symbol keys, it's not really important.

**Comment by JonasIsensee** [comment]
hm, `tmpsave` still uses `bson` as the default. 
That will break since `BSON` is no longer a dependency of DrWatson

**Comment by Datseris** [comment]
then we merge it with the `savename` PR for 2.0.

**Comment by JonasIsensee** [comment]
Alright.

I implemented my suggestion in the latest commit
and adapted test + real_world example

**Comment by Datseris** [comment]
you need to update the docstring of `tmpsave` accordinhgly though

**Pull request merged**
