### PR TITLE
Fix collect_results! bug

### PR DESCRIPTION
**Pull request by nmheim**
Described in #154

### CODE REVIEW

**Comment by JonasIsensee** [comment]
Looks good to me.
Thank you for your help!

**Comment by Datseris** [comment]
The patch version should have been bumped in the PR, so that we could immediately a new release. @JonasIsensee please tag the bug fix when you can.

Related, but not necessary for the PR: I'm pretty sure this DataFrames change broke some "real world examples", we should have a look.

**Comment by JonasIsensee** [comment]
uh, I'm sorry, would you remind me how I do that?

**Comment by Datseris** [comment]
Once the version number in `Project.toml` is updated, it is as simple as going into the "commits" (main page) and writing as a comment: @JuliaRegistrator register()

**Pull request merged**
