### PR TITLE
Improve tag functions and macros

### PR DESCRIPTION
**Pull request by sebastianpech**
Implements #84. I'll also add #83, so this is still a draft.

The problems with having kw and non-kw versions are the following:

**Methods:** The definition of the kw-function also creates a method without the keywords. However, this method is also defined by the optional args function defintion. So on `using` you get a warning that the method is overwritten. My solution here is to define one additional argument, in the non-kw function, as mandatory. So dispatch works like this now:
- If this argument is not given -> dispatch on the kw-version
- If it is given -> dispatch on the non-kw-version

**Macros:** This one is a little tricky. During dispatch one can't tell if the passed `args...` to the macro are kw-definitions or not eg:
```
julia> :(@__DIR__)|>typeof
Expr
julia> :(x=10)|>typeof
Expr
```
The solution now basically works like this.
1. Collect mandatory and optional arguments
2. Check if all optional arguments could be kw-definitions
3. If yes, splat them as keywords
3. If no, splat them in order they were given and then splat the remaining optional arguments, if any.

### CODE REVIEW

**Comment by sebastianpech** [comment]
Any clue why it sometimes failes on mac? It looks pretty random to me, though it seems to always fail with this error:
```
Project Setup: Test Failed at /Users/travis/build/JuliaDynamics/DrWatson.jl/test/project_tests.jl:45
  Expression: projectname() == name
   Evaluated: "test project" == "lala"
```
Is there some async action going on in `initialize_project` such that sometimes the folder is not yet created?

**Comment by Datseris** [comment]
Yeah, the macro version is tough, but you don't have to do this in this PR. If you feel it is difficult or too tricky, just drop it and we can have a look later.

> My solution here is to define one additional argument, in the non-kw function, as mandatory. 

I agree. Maybe it is a good opportunity to *deprecate* the non-kw version?

I don't know about the error you cite. I have seen it before and the solution for was always to just restart tests :P Maybe its time to be opened as a formal issue? but still, I don't really know why it happens :P

**Comment by sebastianpech** [comment]
Ok. Strange. Macro version is done ;)

**Comment by Datseris** [comment]
It would be tricky adding a deprecation warning here, since the low-level method is the non-kw. Instead let's just replace the documentation string to display only the keyword version.

**Comment by sebastianpech** [comment]
Oh yes. But I can just change the call order

**Comment by sebastianpech** [comment]
Thanks for updating the changelog

**Pull request merged**
