### PR TITLE
remove infinite spam from QUACKTIVATE and add @quickactivate

### LINKED ISSUE #109: Make `quickactivate` do nothing if the project is already active.
I find it ridicoulous to be constantly spammed with
```
Activating environment at `C:\Users\datseris\ownCloud\MyScience\Projects\Klein Tunneling in Graphene\kwant_graphene\Project.toml`
```
when this project is already active...

I personally find `quickactivate` super convenient, so every script I ever write starts with this function.

Maybe it is a good idea to make it do nothing if the project-to-be-activated is already active? Or maybe there is some drawback in this?

So what I am asking is whether there is any benefit whatsoever into activating again the already active project.

### PR DESCRIPTION
**Pull request by Datseris**
Closes #109

### CODE REVIEW

**Comment by Datseris** [comment]
I think when I'll give a talk about DrWatson I will replace all quickactivate with quacktivate and pretend like nothing happened. Found Fredrik's comment super funny hahaha

**Comment by asinghvi17** [comment]
`const quacktivate = quickactivate` :D

**Comment by sebastianpech** [comment]
What's your opinion on a short version of `quickactivate(@__DIR__)` like `@quickactivate`? I actually never use anything else than @__DIR__.

**Comment by tamasgal** [comment]
As long as it does not break backwards compatibility, I think that's fine ;) I actually sometimes use relative folders (like `..`)

**Comment by sebastianpech** [comment]
`const 🦆 = quickactivate`

**Comment by Datseris** [comment]
@sebastianpech this is an absolutely mindblowing suggestion. I also only use `@__DIR__`, and your suggestion is totally nonbreaking so all is good. We could also have a 2 argument version of the macro, like
```julia
@quickactivate "project name"
```
which would do the current version does (i.e. check they are the same otherwise error).

**Comment by sebastianpech** [comment]
Good point. You wan't to add it to this PR or should I make an extra one?

**Comment by Datseris** [comment]
meh let's just add it here (but increase to 1.6)

**Comment by sebastianpech** [comment]
hmm it seems i cant push to the project branch

**Comment by sebastianpech** [comment]
`@__DIR__` is a special one ;)

**Comment by sebastianpech** [comment]
I'm currently on the go. Will add doc and bump version later

**Comment by Datseris** [comment]
Good job, thanks!

**Comment by Datseris** [comment]
@sebastianpech sorry, I didn't read your comment about docs and I already did a lot of changes.

You can read and give feedback if I missed something you wanted to do.

**Comment by sebastianpech** [comment]
Thanks, looks good

**Pull request merged**
