### PR TITLE
Fix #223 and #224

### LINKED ISSUE #223: dict_list_count returns wrong number of elements with @onlyif
`dict_list_count` shows a different number than the resulting size of `dict_list`.

Here is a MWE : 

```julia
dict = Dict(
    :a => [1, 2, 3],
    :b => [1:9..., @onlyif(:a > 1, collect(10:10:99))..., @onlyif(:a > 2, collect(100:100:1000))...] # I did not find a nicer way to write this
)

length(dict_list(dict)) == 55
dict_list_count(dict) == 84
```

With julia 1.5 and DrWatson 1.16.6

### LINKED ISSUE #224: Submodules flag not working in older versions of git.
**Describe the bug**
When using `git version 1.8.3.1`, `gitpatch` causes
```
fatal: Failed to parse --submodule option parameter: 'diff'
┌ Warning: `gitpatch` failed with error ProcessFailedException(Base.Process[Process(`git --git-dir=<my_path>/.git --work-tree=<my_path> diff --submodule=diff HEAD`, ProcessExited(128))]), returning `nothing` instead.
```

**Minimal Working Example**
```julia
using DrWatson
DrWatson.gitpatch()
```

**DrWatson.jl version**
DrWatson, version 1.16.5 and newer.
Caused by https://github.com/JuliaDynamics/DrWatson.jl/pull/212
Git version 1.8.3.1.
Works on 1.16.4.

Would it be possible to check for the git version and use newer version with submodules only when git itself supports it, so it wouldn't break when using older git?
Thanks.

### PR DESCRIPTION
**Pull request by sebastianpech**
Closes #223, Closes #224

### CODE REVIEW

**Comment by sebastianpech** [comment]
I checking the message of stderr from the git process contains both --submodule and diff (To circumvent problems with error messages in other languages and also not needing to find out which version of git supports submodule ;) ). If they are both contained, the function now retries without the submodule option. If it still fails the error is printed as before.

**Comment by sebastianpech** [comment]
@racinmat can you maybe check if that works on your machine?

**Review by Datseris — APPROVED** [review]
Gotta admit, this CodeCov stuff is making reviews much harder than they should be.

**Comment by Datseris** [comment]
@sebastianpech what's the status here? is this good to go? (If someone approves the PR and you think it is good to go, feel free to merge at your leisure!)

**Comment by sebastianpech** [comment]
@Datseris I was hoping that maybe @racinmat might verify that the code works on the older git version. Will merge in the next days.

**Comment by racinmat** [comment]
I'll verify it on monday.

**Comment by racinmat** [comment]
So, I'm confirming that with this fix, `gitpatch()` works, while on the newest stable DrWatson version it does not. 
Looking forward to see this merged.

**Pull request merged**
