### PR TITLE
Add `isdirty(gitpath = projectdir())` function

### PR DESCRIPTION
**Pull request by dingraha**
First try at addressing issue #263

### CODE REVIEW

**Comment by Datseris** [comment]
Seems pretty good to me! 

* You can use this function inside `tag!` and replace it's raw logic with using the function
* You also need to add it to the docs for users to see it. I'd suggest adding just after `gitpatch` in `docs/src/save.md`

**Comment by dingraha** [comment]
Great, thanks for the feedback.
> * You can use this function inside `tag!` and replace it's raw logic with using the function

Ah, I think you mean that instead of checking if the `patch` returned by `gitpatch` is something other than `""` or `nothing`, `tag!` could use `isdirty`? The worry I have is that `isdirty` as it exists right now can error (if the path passed to it isn't a Git repository, or doesn't exist). That would appear to violate the "never error" rule for DrWatson's saving functions? Would it be better to catch all errors and return `nothing` in `isdirty` (like what's done in `gitdescribe`)?

**Comment by Datseris** [comment]
Yeah I didn't consider the non error part. Then let's leave it as is. Just add the function to the docs and I'll merge.

**Comment by Datseris** [comment]
Thanks @dingraha . I've reduced the amount of new docs a bit by crosslinking things better. Tagging a new release now!

**Pull request merged**
